cli-source = "github:MorpheApp/morphe-desktop"
cli-version = "dev"
patches-source = "github:rushiranpise/morphe-patches"
patches-version = "dev"

[Telegram]
package-name = "org.telegram.messenger.web"
arch = "arm64-v8a"
