name: Morphe

on:
  schedule:
    - cron: '0 11 * * 6'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  WORK_DIR: morphe

jobs:
  build-and-release:
    name: Build and Release
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ env.WORK_DIR }}

    steps:
      - name: Checkout Local Repository
        uses: actions/checkout@v6

      - name: Prepare Workspace
        uses: ./.github/actions/prepare-workspace
        with:
          target-dir: ${{ env.WORK_DIR }}

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: zulu

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Cache Dependencies
        uses: actions/cache@v5
        with:
          path: |
            ~/.cloakbrowser
            ~/.bun/install/cache
          key: ${{ env.WORK_DIR }}-${{ runner.os }}-bun-${{ hashFiles(format('{0}/bun.lock', env.WORK_DIR)) }}

      - name: Install Dependencies
        run: bun install --frozen-lockfile

      - name: Build APKs
        shell: bash
        run: |
          find . -maxdepth 1 -type f -name '*-*.toml' -print0 |
            sort -z |
            while IFS= read -r -d '' config; do
              echo "Building with $config"
              bun run main.ts "$(realpath "$config")"
            done

      - name: Publish Build
        uses: ./.github/actions/publish-build
        with:
          release-title: Morphe Nightly
          release-tag: ${{ env.WORK_DIR }}
          release-glob: '${{ env.WORK_DIR }}/dist/*.apk'
