name: Morphe

on:
  schedule:
    - cron: '0 11 * * 6'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  WORK_DIR: morphe

jobs:
  build-and-release:
    name: Build and Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Local Repository
        uses: actions/checkout@v6

      - name: Prepare Workspace
        uses: ./.github/actions/prepare-workspace
        with:
          target-dir: ${{ env.WORK_DIR }}

      - name: Setup Java Environment
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: zulu

      - name: Setup Bun Environment
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Cache Dependencies
        uses: actions/cache@v5
        with:
          path: |
            ~/.cloakbrowser
            ~/.bun/install/cache
            ${{ env.WORK_DIR }}/node_modules
          key: ${{ env.WORK_DIR }}-${{ runner.os }}-bun-${{ hashFiles(format('{0}/bun.lock', env.WORK_DIR)) }}

      - name: Install Dependencies
        working-directory: ${{ env.WORK_DIR }}
        run: bun install

      - name: Build APKs
        working-directory: ${{ env.WORK_DIR }}
        run: |
          CONFIGS=($(find . -maxdepth 1 -name "*-*.toml" | sort))
          for CONFIG in "${CONFIGS[@]}"; do
            echo "Building with $CONFIG"
            bun run main.ts "$(realpath "$CONFIG")"
          done

      - name: Publish Build and Update SHA
        if: success()
        uses: ./.github/actions/publish-build
        with:
          release-title: Morphe Nightly
          release-tag: ${{ env.WORK_DIR }}
          release-glob: '${{ env.WORK_DIR }}/dist/*.apk'
